import { motion } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import {
  FileText,
  Music,
  Video,
  ShieldCheck,
  Zap,
  Cpu,
  ArrowRight,
  Sparkles,
  Database,
  Search,
} from 'lucide-react';

export default function Home() {
  const navigate = useNavigate();

  const features = [
    {
      title: 'PDF Intelligence',
      description: 'PyMuPDF page-level extraction, token chunking, and instant vector indexing for long papers and contracts.',
      icon: FileText,
      color: 'from-blue-500 to-indigo-600',
      badge: 'PyMuPDF Engine',
    },
    {
      title: 'Audio Intelligence',
      description: 'Local Whisper speech recognition for MP3, WAV, M4A, and FLAC audio files with precision timestamping.',
      icon: Music,
      color: 'from-purple-500 to-pink-600',
      badge: 'Whisper AI',
    },
    {
      title: 'Video Intelligence',
      description: 'FFmpeg audio track extraction paired with Whisper transcription for MP4, MOV, and MKV video files.',
      icon: Video,
      color: 'from-cyan-500 to-blue-600',
      badge: 'FFmpeg + Whisper',
    },
    {
      title: 'Offline Privacy',
      description: 'Zero internet dependencies. All model inference, chunk embeddings, and data storage stay on your machine.',
      icon: ShieldCheck,
      color: 'from-emerald-500 to-teal-600',
      badge: '100% Local',
    },
    {
      title: 'Semantic Search',
      description: 'Cosine similarity matching over all-MiniLM-L6-v2 vector embeddings stored persistently in ChromaDB.',
      icon: Zap,
      color: 'from-amber-500 to-orange-600',
      badge: 'ChromaDB Top-K',
    },
    {
      title: 'Local LLM Generation',
      description: 'Streaming context-aware answers generated by local Ollama (Llama 3.2) with strict zero-hallucination prompts.',
      icon: Cpu,
      color: 'from-rose-500 to-red-600',
      badge: 'Ollama Llama 3.2',
    },
  ];

  return (
    <div className="min-h-full bg-[#07090e] bg-radial-mesh text-slate-100 p-6 md:p-12 space-y-12">
      {/* Hero Section */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="max-w-4xl mx-auto text-center space-y-6 pt-6"
      >
        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass-panel border-indigo-500/30 text-indigo-300 text-xs font-semibold tracking-wide shadow-lg">
          <Sparkles size={14} className="text-indigo-400" />
          <span>Next-Generation Offline Intelligence</span>
        </div>

        <h1 className="text-4xl md:text-6xl font-extrabold tracking-tight text-white leading-tight">
          Offline Multimodal <br />
          <span className="bg-gradient-to-r from-indigo-400 via-purple-400 to-cyan-400 bg-clip-text text-transparent">
            AI Knowledge Hub
          </span>
        </h1>

        <p className="text-lg md:text-xl text-slate-400 max-w-2xl mx-auto font-normal leading-relaxed">
          Query PDFs, Audio and Video files entirely offline using local AI.
        </p>

        <div className="flex flex-wrap items-center justify-center gap-4 pt-4">
          <button
            onClick={() => navigate('/')}
            className="flex items-center gap-2.5 px-6 py-3.5 rounded-xl bg-gradient-to-r from-indigo-600 via-purple-600 to-cyan-600 text-white font-semibold text-sm shadow-xl hover:shadow-indigo-500/25 hover:scale-[1.02] transition-all"
          >
            <Search size={18} />
            <span>Open Knowledge Workspace</span>
            <ArrowRight size={16} />
          </button>

          <button
            onClick={() => navigate('/studio')}
            className="flex items-center gap-2 px-6 py-3.5 rounded-xl glass-panel hover:bg-slate-800/60 text-slate-200 font-semibold text-sm transition-all border-slate-700"
          >
            <Database size={18} className="text-indigo-400" />
            <span>Launch Multimodal Studio</span>
          </button>
        </div>
      </motion.div>

      {/* Feature Grid Header */}
      <div className="max-w-6xl mx-auto pt-8">
        <div className="text-center space-y-2 mb-10">
          <h2 className="text-2xl md:text-3xl font-bold text-white tracking-tight">
            Core Multimodal Capabilities
          </h2>
          <p className="text-slate-400 text-sm">
            High-performance local vector indexing and inference architecture.
          </p>
        </div>

        {/* 6 Feature Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((feat, index) => {
            const Icon = feat.icon;
            return (
              <motion.div
                key={feat.title}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                className="glass-card glass-card-hover p-6 rounded-2xl relative overflow-hidden flex flex-col justify-between"
              >
                <div className="space-y-4">
                  <div className="flex items-center justify-between">
                    <div className={`p-3.5 rounded-xl bg-gradient-to-r ${feat.color} shadow-lg text-white`}>
                      <Icon size={22} />
                    </div>
                    <span className="text-[11px] font-medium px-2.5 py-1 rounded-full bg-slate-800/80 text-slate-300 border border-slate-700/60">
                      {feat.badge}
                    </span>
                  </div>

                  <h3 className="text-lg font-bold text-white tracking-wide">
                    {feat.title}
                  </h3>

                  <p className="text-slate-400 text-sm leading-relaxed">
                    {feat.description}
                  </p>
                </div>
              </motion.div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
